import init from "../migrations/0000_init.sql?raw";
import providerConfigs from "../migrations/0001_provider-configs.sql?raw";
import skillsPluginsMcp from "../migrations/0002_skills-plugins-mcp.sql?raw";
import teams from "../migrations/0003_teams.sql?raw";

export interface EmbeddedMigration {
  readonly id: string;
  readonly sql: string;
}

/**
 * Migrations generated by drizzle-kit and embedded at build time. Add new files
 * here in order; ids are stable and recorded in the `__migrations` table.
 */
export const migrations: EmbeddedMigration[] = [
  { id: "0000_init", sql: init },
  { id: "0001_provider_configs", sql: providerConfigs },
  { id: "0002_skills_plugins_mcp", sql: skillsPluginsMcp },
  { id: "0003_teams", sql: teams },
];
